# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41cc487fa7121d186a88be18942f1b2d70f9ea82a28971cfde25b1b29a2b7bbbb5830fdedf92346861e555132212f78b8c4cc0f085ce83567ed9e1b1d879af60

test:
  secret_key_base: 92f2966be4dd781638383ede660ca7ad0b4373ea231725b8b379ca729e2e707931b1bf73149ec18f6bcd85c01bf50b8bc05d8a3a854912e3311f5aac63536938

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
