# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64f3740086430296a33c036ab2690550fb5fe84a219681fe74004218104bd111f1c794121aa539d50cd007b05e16ae70c410e5a51724f4b343e7d540be7e01c6

test:
  secret_key_base: 758f9cd78af793185f3189856ce6a7851e794266addbc9d745e93839cda3126a4b1eb94ae351b16db8b42a605569f613d851a1ec24afea4cbd50aae2ccc323f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
